Main page has been fully CSSed.
dl-academy-edu/bo-prokopenko-daniil-2 pull request #3
Opened 2021-04-13 09:01 UTC by ProkopenkoDaniil-I

Main page has been fully CSSed.

2021-04-13 09:03 UTC, ProkopenkoDaniil-I commented
Main page has been fully CSSed.

2021-05-04 08:07 UTC, MitrofanovaO requested changes

2021-05-04 08:07 UTC, MitrofanovaO commented on index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@1,400;1,700&display=swap" rel="stylesheet">
все три ссылки на шрифты можно объединить с одну, когда ты добавляешь их себе (кнопка select this style на сайте fonts.google.com ) сбоку появляется панель Selected family и если добавить несколько шрифтов, получится одна ссылка (google сам тебе её построит, останется скопировать)

2021-05-04 08:07 UTC, MitrofanovaO commented on index.html
> +            <img src="Images/logo-dlk.svg" alt="" >
Опять вижу путь с заглавной буквы Images

2021-05-04 08:07 UTC, MitrofanovaO commented on index.html
> +                <li class="brand-item"><a href="#"><img src="images/brands-owox.svg" alt=""></a></li>
вот тут уже нормальный путь, хотя до этого был как раз тоже с заглавной буквы (как так? не везде исправил?)

2021-05-06 07:18 UTC, MitrofanovaO requested changes

2021-05-06 07:18 UTC, MitrofanovaO commented on css/catalog_detail.css
> +}
Почему сделал background-image? Надо вставить в html именно картинки (img)

2021-05-06 07:18 UTC, MitrofanovaO commented on css/catalog_style.css
> +}
Тут такая же ситуация, нужны картинки в html (если работать с данными из админки в дальнейшем, бэкенден будет передавать данные в html, сейчас ты их прописываешь в стили, в этой ситуации это не правильно)

2021-05-06 07:18 UTC, MitrofanovaO commented on css/contacts_style.css
> +
Лишние пробелы по файлам надо удалить, они у тебя много где

2021-05-06 07:18 UTC, MitrofanovaO commented on css/style.css
> +}
Опять background-image

2021-05-06 07:18 UTC, MitrofanovaO commented on css/style.css
> +}
у тебя стили одинаковые, пропиши через запятую классы и состояния чтобы не дублировать код

2021-05-06 07:18 UTC, MitrofanovaO commented on css/style.css
> +    background-color: rgba(112, 187, 220, 0.2);;
две запятые

2021-05-06 07:18 UTC, MitrofanovaO commented on css/style.css
> +}
Данный блок можно сверстать без абсолюта. Почему это не правильно, смотри у тебя будет текст больше чем есть сейчас, например добавь туда ещу несколько слов и у тебя будут слова заезжать на нижний текст, такого быть не должно! Каждый блок смотри на переполняемость контектом, чтобы нигде верстка не ехала. При проверке у нас есть такой критерий, сейчас ты его не выполнил 
![image](https://user-images.githubusercontent.com/24611929/117252348-dfcb5f80-ae56-11eb-937a-8472f4bbcdf8.png)

2021-05-06 07:18 UTC, MitrofanovaO commented on index.html
> +                <a href="#" class="dl_digital-link">Web Design — Direct Line Development</a>
нет правильного ховера на ссылку + цвет ссылки изначально не правильный не по макету

2021-05-06 07:18 UTC, MitrofanovaO commented on index.html
> +        </div>
Логотип должен быть ссылкой, на других страницах при клике на лого мы должны иметь возможность вернуться на главную страницу, сейчас прочему то у него есть просто ховер

2021-05-06 07:18 UTC, MitrofanovaO commented on index.html
> +                <li class="brand-item"><a href="#"><img src="images/brands-mailru.svg" alt=""></a></li>
нет ховера на партнерах (у тебя же тут ссылка есть, надо дать понять пользователю что можно перейти на страницу партнера)

2021-05-06 07:18 UTC, MitrofanovaO commented on index.html
> +                        <input type="email" placeholder="Email" id="email1" class="footer-input-field">
отступ слева у placeholder надо сделать 15px и цветом он у тебя отличается от макета

2021-05-06 07:18 UTC, MitrofanovaO commented on index.html
> +                    <li>
куда твиттер делся? 
![image](https://user-images.githubusercontent.com/24611929/117255572-d93ee700-ae5a-11eb-8536-ee7cc2b00893.png)

2021-05-06 07:18 UTC, MitrofanovaO commented on index.html
> +                     </a>
нет ссылки на существующую страницу (она у тебя уже есть)

2021-05-06 07:18 UTC, MitrofanovaO commented on index.html
> +                <a href="pages/contacts.html" class="header-contact-us">Contact us</a>
неправильная ссылка на страницу

2021-05-06 07:18 UTC, MitrofanovaO commented on index.html
> +            <section class="footer-section">
отступ сверху у футера не по макету (очень маленький) 
![image](https://user-images.githubusercontent.com/24611929/117256442-c24cc480-ae5b-11eb-9ef8-20566fdaa2e0.png)

2021-05-06 07:18 UTC, MitrofanovaO commented on css/catalog_style.css
> +}
на главной есть ховер на блоках каталога, а на странице каталога их нет

2021-05-06 07:18 UTC, MitrofanovaO commented on pages/catalog/detail.html
> +    </header>
пройдись по всем страницам, не у всех корректно работает menu в header (пути прописаны неправильно)

2021-05-06 07:18 UTC, MitrofanovaO commented on css/blog_style.css
> +}
нет ховера на блок как на макете

2021-05-14 12:23 UTC, closed without merging